id: 6f6dadff534b4e868c4687c1e7c721e9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_309-The_Sutra_on_Impermanence-v1
  language: bo
  author: ''
  volume: {}
